### ISSUE TITLE
CmcComparison returns NaN when comparing some inputs

### ISSUE THREAD

**Issue by madelson** [THEjoezack/ColorMine#41]
Here's an example:

```
var a = new Rgb { R = 0, G = 0, B = 0 };
var b = new Rgb { R = 110, G = 153, B = 201 };
var cmc = new CmcComparison();
Console.WriteLine(cmc.Compare(a, b)); // NaN
```

I'm using version 1.1.3 from NuGet.

**Comment by tompazourek** [comment]
It's answered in the issue placed just before you: #40

**Comment by THEjoezack** [comment]
Fixed in https://github.com/THEjoezack/ColorMine/pull/46

**Comment by THEjoezack** [comment]
Fixed in https://github.com/THEjoezack/ColorMine/pull/46

**Comment by madelson** [comment]
Thanks @THEjoezack !
